name = "yarn"
description = "yarn package manager hooks"
entry_point = "main.ts"

[permissions]
run = ['/tmp', 'yarn']
read = ['~/.cache/node/corepack', '~/.yarn', '/tmp', './']
write = ['~/.yarn', '/tmp', './']
net = true
