name = "yarn"
description = "yarn package manager hooks"
entry_point = "main.ts"

[permissions]
run = ['yarn', 'node', "/usr/bin", "/tmp"]
read = ['./', '~/.cache/node/corepack', '~/.yarn']
write = ['./', '/tmp',
#TODO
'~/.yarn',
]
net = true
