[package]
name = "projects_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
phylum_types = { git = "https://github.com/phylum-dev/phylum-types", branch = "development" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }
