# Modified Release github action. Replace the current with this when ready.
---
name: Release New

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install host dependencies
        run: |
          sudo add-apt-repository -y ppa:dysfunctionalprogramming/minisign
          sudo apt update
          sudo apt install -yq build-essential zip minisign
      - name: Checkout the repo
        uses: actions/checkout@master
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Distributions
        run: cargo xtask dist
      # TODO: determine if it makes more sense to sign the entire zipfile or just the binaries w/i the zipfiles
      - name: Sign binaries
        run: |
          echo -e $MINISIGN_KEY > minisign.key
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-linux-x86_64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-macos-x86_64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
          echo $MINISIGN_PASSWORD | minisign -Sm target/dist/phylum-macos-aarch64/phylum -s minisign.key -t 'Phylum - Future of software supply chain security'
        env:
          MINISIGN_KEY: ${{ secrets.MINISIGN_KEY }}
          MINISIGN_PASSWORD: ${{ secrets.MINISIGN_PASSWORD }}
      - name: Build zipfiles
        working-directory: ./target/dist
        run: |
          zip -r phylum-linux-x86_64.zip phylum-linux-x86_64
          zip -r phylum-macos-x86_64.zip phylum-macos-x86_64
          zip -r phylum-macos-aarch64.zip phylum-macos-aarch64
      - name: Determine prerelease status
        uses: haya14busa/action-cond@v1
        id: preRelease
        with:
          cond: ${{ contains(github.ref, 'rc') }}
          if_true: 'true'  # string value
          if_false: 'false'  # string value
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: ${{ steps.preRelease.outputs.value }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./target/dist/phylum-*.zip
