---
name: Test

on:
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - alarm
  # Run weekly on the default branch to make sure it always builds with the latest rust release
  schedule:
    - cron: '30 5 * * 1'

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          profile: minimal
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target aarch64-unknown-linux-musl
  shellcheck:
    # TODO: Update to `ubuntu-latest` once `ubuntu-22.04` support is stabilized.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Script Style Check
        if: github.event_name != 'schedule'
        run: shellcheck -o all -S style -s sh $(find . -iname "*.sh")

  musl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker run -v "$PWD":/usr/src/cli -w /usr/src/cli rust:alpine3.16 entrypoint.sh

  # This job reports the results of the test matrix above
  test:
    if: always()
    needs: test-matrix
    runs-on: ubuntu-latest
    steps:
      - if: needs.test-matrix.result != 'success'
        name: Fail the build
        run: exit 1
